export const NEW_SLIDER_REQUEST = 'NEW_SLIDER_REQUEST';
export const NEW_SLIDER_SUCCESS = 'NEW_SLIDER_SUCCESS';
export const NEW_SLIDER_RESET = 'NEW_SLIDER_RESET';
export const NEW_SLIDER_FAIL = 'NEW_SLIDER_FAIL';

export const GET_ALL_SLIDERS_SUCCESS = 'GET_ALL_SLIDERS_SUCCESS';
export const GET_ALL_SLIDERS_FAIL = 'GET_ALL_SLIDERS_FAIL';

export const GET_SLIDER_DETAILS_SUCCESS = 'GET_SLIDER_DETAILS_SUCCESS';
export const GET_SLIDER_DETAILS_FAIL = 'GET_SLIDER_DETAILS_FAIL';

export const ADMIN_SLIDERS_REQUEST = 'ADMIN_SLIDERS_REQUEST';
export const ADMIN_SLIDERS_SUCCESS = 'ADMIN_SLIDERS_SUCCESS';
export const ADMIN_SLIDERS_FAIL = 'ADMIN_SLIDERS_FAIL';

export const UPDATE_SLIDER_REQUEST = 'UPDATE_SLIDER_REQUEST';
export const UPDATE_SLIDER_SUCCESS = 'UPDATE_SLIDER_SUCCESS';
export const UPDATE_SLIDER_RESET = 'UPDATE_SLIDER_RESET';
export const UPDATE_SLIDER_FAIL = 'UPDATE_SLIDER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
